services:
  - type: web
    name: project-dashboard-backend
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DATABASE_URL
        value: postgresql://projectuser:aroQ42eH1dJ75YHHejJb1On3dTHCxYQ3@dpg-d27ruomuk2gs73ejfkj0-a.oregon-postgres.render.com/project_dashboard_67v7
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: CORS_ORIGINS
        value: "*"
      - key: CARGO_HOME
        value: /tmp/cargo
      - key: RUSTUP_HOME
        value: /tmp/rustup
      - key: CARGO_TARGET_DIR
        value: /tmp/target
      - key: CARGO_REGISTRY_CACHE
        value: /tmp/cargo/registry/cache 